name: Branch Naming Policy

on:
  create:
  delete:
  pull_request:
    branches:
      - master

jobs:
  branch-naming-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Branch Naming Policy Action
        uses: nicklegan/github-repo-branch-naming-policy-action@v1.1.0
        if: github.ref_type == 'branch' || github.ref_type == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          regex: '^(feature|bugfix|hotfix|tests)\/STONES\-\d+[a-z0-9\-_]+$'
        # flags: i
        # token: ${{ secrets.REPO_TOKEN }}
        # delete: true