name: Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          pipx install poetry
          poetry self add poetry-plugin-export

      - name: Cache Poetry cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/artifacts
            ~/.cache/pypoetry/cache
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-cache-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-cache-

      - name: Set up Python 🤖
        uses: actions/setup-python@v4.4.0
        with:
          # either pin to a specific patch release...
          python-version: '3.10.12'
          # ...or allow any 3.10.x:
          # python-version: '3.10'
          cache: poetry
          check-latest: false
          update-environment: true

      - name: Install poetry dependencies
        run: make install

      - name: Analysing the code with pylint
        run: make lint
